#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
#set -o pipefail

# Configure auto-login
sed -i 's/ExecStart=-\/sbin\/agetty --noclear \%I \$TERM/ExecStart=-\/sbin\/agetty --autologin cc --noclear \%I \$TERM/g' /etc/systemd/system/getty.target.wants/getty\@tty1.service
